---
Function: rulesGenerator
Environment: null
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/rulesGenerator-role-ahar4epa
Runtime: nodejs24.x
Timeout: 123
---
Function: FundDocumentProcessingWorkerLambda
Environment:
  Variables:
    BEDROCK_MODEL_ID: amazon.nova-pro-v1:0
    DDB_TABLE: FundProcessingStatus
    DOC_BUCKET: highcloud-rulesgen
    PROMPT_KEY: icmemoextractionprompt.txt
    SCHEMA_KEY: icmemoschema.json
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/FundDocumentProcessingWorkerLambda-role-yof1iwi0
Runtime: nodejs24.x
Timeout: 120
---
Function: ExtractICMemoLambda
Environment:
  Variables:
    BEDROCK_MODEL_ID: amazon.nova-pro-v1:0
    DDB_TABLE: FundProcessingStatus
    DOC_BUCKET: highcloud-rulesgen
    PROMPT_KEY: icmemoextractionprompt.txt
    SCHEMA_KEY: icmemoschema.json
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/ExtractICMemoLambda-role-q1qrc7s9
Runtime: nodejs24.x
Timeout: 63
---
Function: FundGetByIdLambda
Environment:
  Variables:
    DYNAMODB_TABLE: FundProcessingStatus
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/FundGetByIdLambda-role-v1xsh5gz
Runtime: nodejs24.x
Timeout: 63
---
Function: FundDocumentUploadLambda
Environment:
  Variables:
    DOCUMENTS_BUCKET: highcloud-rulesgen
    DYNAMODB_TABLE: FundProcessingStatus
    PROCESSING_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/293883686626/RulesGenQueue
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/FundDocumentUploadLambda-role-wj3bjoic
Runtime: nodejs24.x
Timeout: 63
---
Function: CreateFundUpload
Environment:
  Variables:
    DDB_TABLE: FundProcessingStatus
    DOC_BUCKET: highcloud-rulesgen
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/CreateFundUpload-role-xnomahmb
Runtime: nodejs24.x
Timeout: 63
---
Function: FundDocumentProcessorLambda
Environment:
  Variables:
    BEDROCK_MODEL_ID: amazon.nova-pro-v1:0
    DDB_TABLE_NAME: FundProcessingStatus
    PROMPT_S3_URI: s3://highcloud-rulesgen/prompts/rules-engine-v1.txt
    SUCCESS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/293883686626/FundRulesProcessingSuccessQueue
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/FundDocumentProcessorLambda-role-711rp0hi
Runtime: nodejs24.x
Timeout: 63
---
Function: FundProcessingStatusLambda
Environment:
  Variables:
    DDB_TABLE_NAME: FundProcessingStatus
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/FundProcessingStatusLambda-role-sngnd8ou
Runtime: nodejs24.x
Timeout: 3
---
Function: FundUploadCompleteLambda
Environment:
  Variables:
    BUCKET_NAME: highcloud-rulesgen
    DYNAMODB_TABLE: FundProcessingStatus
    SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/293883686626/RulesGenQueue
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/FundUploadCompleteLambda-role-rbz7aurf
Runtime: nodejs24.x
Timeout: 63
---
Function: FundInitUploadLambda
Environment:
  Variables:
    DDB_TABLE_NAME: FundProcessingStatus
    DOCUMENTS_BUCKET: highcloud-rulesgen
    PRESIGN_EXPIRES_SECONDS: '900'
Handler: index.handler
Layers: null
MemorySize: 128
Role: arn:aws:iam::293883686626:role/service-role/FundInitUploadLambda-role-g54al4qm
Runtime: nodejs24.x
Timeout: 3
